server:
  port: 9010
spring:
  application:
    name: ExamStuProvider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coe?serverTimezone=GMT%2B8
    username: root
    password: 123456
eureka:
  instance:
    instance-id: ExamStuProvider:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000